# Generated by Django 2.2.4 on 2019-09-15 08:38

from django.db import migrations


def insert_data_into_field_new_bulding(apps, schema_editor):
    Flat = apps.get_model('property', 'Flat')
    for flat in Flat.objects.all():
        if flat.construction_year >= 2015:
            flat.new_bulding = True
            flat.save()
        else:
            flat.new_bulding = False
            flat.save()


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0003_flat_new_bulding'),
    ]

    operations = [
        migrations.RunPython(insert_data_into_field_new_bulding),
    ]
