# Generated by Django 2.2.4 on 2019-09-15 11:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0004_auto_20190915_1205'),
    ]

    operations = [
        migrations.RenameField(
            model_name='flat',
            old_name='new_bulding',
            new_name='new_building',
        ),
    ]
