# Generated by Django 2.2.4 on 2019-09-17 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0010_auto_20190917_1016'),
    ]

    operations = [
        migrations.AlterField(
            model_name='owner',
            name='flats',
            field=models.ManyToManyField(blank=True, to='property.Flat', verbose_name='Квартиры в собственности'),
        ),
    ]
