# Generated by Django 2.2.4 on 2019-09-17 09:04

from django.db import migrations
import phonenumbers

def transfer_data_to_owner(apps, schema_editor):
    Flat = apps.get_model('property', 'Flat')
    Owner = apps.get_model('property', 'Owner')

    for flat in Flat.objects.all():
        full_name = flat.owner_1
        phonenumber = flat.owners_phonenumber
        phone_pure = flat.owner_phone_pure

        number = phonenumbers.parse(flat.owners_phonenumber, 'RU')

        if phonenumbers.is_valid_number(number):
            formatted_number = phonenumbers.format_number(number, phonenumbers.PhoneNumberFormat.E164)
            phone_pure = formatted_number
        else:
            phone_pure = ''

        Owner.objects.get_or_create(
            full_name=full_name, 
            phonenumber=phonenumber, 
            phone_pure=phone_pure
        )



class Migration(migrations.Migration):

    dependencies = [
        ('property', '0011_auto_20190917_1021'),
    ]

    operations = [
        migrations.RunPython(transfer_data_to_owner),
    ]
