# Generated by Django 2.2.4 on 2019-09-29 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0013_auto_20190917_1348'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flat',
            name='owner_1',
            field=models.CharField(db_index=True, max_length=200, verbose_name='ФИО владельца'),
        ),
    ]
