# Generated by Django 2.2.4 on 2019-09-29 19:07

from django.db import migrations


def associate_flats_with_owners(apps, schema_editor):
    Flat = apps.get_model('property', 'Flat')
    Owner = apps.get_model('property', 'Owner')

    for owner in Owner.objects.all():
        new_flats = Flat.objects.filter(owner_1=owner.full_name)
        owner.flats.set(new_flats)


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0013_auto_20190917_1348'),
    ]

    operations = [
        migrations.RunPython(associate_flats_with_owners),
    ]
