# Generated by Django 2.2.4 on 2019-09-29 19:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0015_auto_20190929_2207'),
        ('property', '0014_auto_20190929_2207'),
    ]

    operations = [
    ]
