# Generated by Django 2.2.4 on 2019-10-07 15:24

from django.db import migrations


def set_owner_value(apps, schema_editor):
    Flat = apps.get_model('property', 'Flat')
    Owner = apps.get_model('property', 'Owner')


    for flat in Flat.objects.all():
        new_owner = Owner.objects.filter(flats__id__exact=flat.id).first()
        flat.owner = new_owner
        flat.save()


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0017_auto_20191007_1823'),
    ]

    operations = [
        migrations.RunPython(set_owner_value),
    ]
